// src/Experience.tsx
import { Milestone } from "./models";
import experienceJson from "./data/experience.json";

function Experience() {
  const experience = experienceJson as Milestone[];

  return (
    <div className="card" id="experience">
      <div className="card-content">
        <div className="info">
          <div className="header">
            <div className="title">Experience</div>
          </div>
        </div>
        <div className="milestones">
          {experience.map((e) => (
            <div className="milestone" key={e.title! + e.date}>
              <div className="image">
                <img src={"/img/" + e.image} />
              </div>
              <div className="info">
                <div className="title">{e.title}</div>
                <div className="subtitle">{e.subtitle}</div>
              </div>
              <div className="date">{e.date}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default Experience;

// adam-swanson-site/src/app/home/experience/experience.component.ts
import { Component, OnInit } from '@angular/core';
import { Milestone } from 'src/app/models';
import { DataService } from 'src/app/services/data.service';

@Component({
  selector: 'app-experience',
  templateUrl: './experience.component.html',
  styleUrls: ['./experience.component.scss']
})
export class ExperienceComponent implements OnInit {

  experience: Milestone[];

  constructor(private dataService: DataService) { }

  ngOnInit(): void {
    this.experience = this.dataService.getExperience();
  }

}

<div class="card" id="experience">
  <div class="card-content">
    <div class="info">
      <div class="header">
        <div class="title">Experience</div>
      </div>
    </div>
    <div class="milestones">
      <div class="milestone" *ngFor="let milestone of experience">
        <div class="image">
          <img [src]="'assets/img/' + milestone.image" />
        </div>
        <div class="info">
          <div class="title">{{milestone.title}}</div>
          <div class="subtitle">{{milestone.subtitle}}</div>
        </div>
        <div class="date">
          {{milestone.date}}
        </div>
      </div>
    </div>
  </div>
</div>
