// src/Skills.tsx
import React from "react";
import "./Skills.scss";
import skillsJson from "./data/skills.json";
import { Skill, CategoricalSkills } from "./models";

function Skills() {
  const skillsImagesPath = process.env.PUBLIC_URL + "/img/skills";
  const skills = skillsJson as CategoricalSkills[];
  const categories = skills
    .map((s) => s.category)
    .filter((value, i, ar) => ar.indexOf(value) === i);

  const getSkills = (category: string) => {
    return skills.find((s) => s.category === category)?.skills ?? [];
  };

  const getImagePath = (skill: Skill, category: string) => {
    return `${skillsImagesPath}/${category.toLowerCase()}/${
      skill.imageName
    }.png`;
  };

  return (
    <div className="card" id="skills">
      <div className="card-content">
        <div className="info">
          <div className="header">
            <div className="title">Skills</div>
          </div>
        </div>
        <div className="skills-list">
          {categories.map((c) => (
            <div className="category" key={c}>
              <div className="title">{c}</div>
              <div className="skills">
                {getSkills(c!).map((s) => (
                  <div className="skill" key={s.name}>
                    {s.imageName && (
                      <div className="image">
                        <img src={getImagePath(s, c!)} />
                      </div>
                    )}
                    <div className="name">{s.name}</div>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default Skills;

// adam-swanson-site/src/app/home/skills/skills.component.ts
import { Component, OnInit } from '@angular/core';
import { Skill, CategoricalSkills } from 'src/app/models';
import { DataService } from 'src/app/services/data.service';

@Component({
  selector: 'app-skills',
  templateUrl: './skills.component.html',
  styleUrls: ['./skills.component.scss']
})
export class SkillsComponent implements OnInit {

  skillsImagesPath = '/assets/img/skills';
  skills: CategoricalSkills[];
  categories: string[];

  constructor(private dataService: DataService) { }

  ngOnInit(): void {
    this.skills = this.dataService.getSkills();
    this.categories = this.getCategories();
  }

  getSkills(category: string): Skill[] {
    return this.skills.find(skill => skill.category === category)?.skills ?? [];
  }
  
  getImagePath(skill: Skill, category: string): string {
    return `${this.skillsImagesPath}/${category.toLowerCase()}/${skill.imageName}.png`;
  }

  private getCategories(): string[] {
    return this.getUniqueValues(this.skills.map(skill => skill.category));
  }

  private getUniqueValues(values: any[]) {
    return values.filter((value, i, ar) => ar.indexOf(value) === i);
  }

}

<div class="card" id="skills">
  <div class="card-content">
    <div class="info">
      <div class="header">
        <div class="title">Skills</div>
      </div>
    </div>
    <div class="skills-list">
      <div class="category" *ngFor="let category of categories">
        <div class="title">{{category}}</div>
        <div class="skills">
          <div class="skill" *ngFor="let skill of getSkills(category)">
            <div class="image" *ngIf="skill.imageName">
              <img [src]="getImagePath(skill, category)" />
            </div>
            <div class="name">{{skill.name}}</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
