// adam-swanson-site/src/app/home/achievements/achievements.component.ts
import { Component, OnInit } from '@angular/core';
import { Milestone } from 'src/app/models';
import { DataService } from 'src/app/services/data.service';

@Component({
  selector: 'app-achievements',
  templateUrl: './achievements.component.html',
  styleUrls: ['./achievements.component.scss']
})
export class AchievementsComponent implements OnInit {

  achievements: Milestone[];

  constructor(private dataService: DataService) { }

  ngOnInit(): void {
    this.achievements = this.dataService.getAchievements();
  }

}

<div class="card" id="achievements">
  <div class="card-content">
    <div class="info">
      <div class="header">
        <div class="title">Achievements</div>
      </div>
    </div>
    <div class="milestones">
      <div class="milestone" *ngFor="let milestone of achievements">
        <div class="image">
          <img [src]="'assets/img/' + milestone.image" />
        </div>
        <div class="info">
          <div class="title">{{milestone.title}}</div>
          <div class="subtitle">{{milestone.subtitle}}</div>
        </div>
        <div class="date">
          {{milestone.date}}
        </div>
      </div>
    </div>
  </div>
</div>

// src/components/Achievements.tsx
import { Milestone } from "../models";
import achievementsJson from "../data/achievements.json";

function Achievements() {
  const achievements = achievementsJson as Milestone[];

  return (
    <div className="card" id="achievements">
      <div className="card-content">
        <div className="info">
          <div className="header">
            <div className="title">Achievements</div>
          </div>
        </div>
        <div className="milestones">
          {achievements.map((e) => (
            <div className="milestone" key={e.title! + e.date}>
              <div className="image">
                <img src={"/img/" + e.image} />
              </div>
              <div className="info">
                <div className="title">{e.title}</div>
                <div className="subtitle">{e.subtitle}</div>
              </div>
              <div className="date">{e.date}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default Achievements;
