// adam-swanson-site/src/app/home/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { faGithub, faLinkedin, faTwitter } from '@fortawesome/free-brands-svg-icons';
import { faPenSquare } from '@fortawesome/free-solid-svg-icons';
import { SocialItem } from 'src/app/models';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {

  socialItems: SocialItem[] = [
    { icon: faTwitter, href: 'https://twitter.com/crisp2020' },
    { icon: faLinkedin, href: 'https://www.linkedin.com/in/adam-swanson/' },
    { icon: faGithub, href: 'https://github.com/theaswanson' },
    { icon: faPenSquare, href: 'https://blog.layerseven.net' },
  ];

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="header-card">
  <div class="card-content">
    <div class="info">
      <div class="header">
        <div class="title">Adam Swanson</div>
        <div class="subtitle">Software Developer</div>
      </div>
      <div class="icons">
        <div class="icon" *ngFor="let item of socialItems">
          <a [href]="item.href" target="_blank">
            <fa-icon [icon]="item.icon" size="lg"></fa-icon>
          </a>
        </div>
      </div>
    </div>
    <div class="image">
      <img src="/assets/img/adam2.jpg" />
    </div>
  </div>
</div>

// src/components/Header.tsx
import "./Header.scss";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faGithub, faLinkedin } from "@fortawesome/free-brands-svg-icons";
import { faPenSquare } from "@fortawesome/free-solid-svg-icons";
import { SocialItem } from "../models";
import { faTwitterX } from "./faTwitterX";

function Header() {
  const socialItems: SocialItem[] = [
    { icon: faTwitterX, href: "https://x.com/crisp2020" },
    { icon: faLinkedin, href: "https://www.linkedin.com/in/adam-swanson/" },
    { icon: faGithub, href: "https://github.com/theaswanson" },
    { icon: faPenSquare, href: "https://blog.adamswanson.dev" },
  ];

  return (
    <div className="header-card">
      <div className="card-content">
        <div className="info">
          <div className="header">
            <div className="title">Adam Swanson</div>
            <div className="subtitle">Software Developer</div>
          </div>
          <div className="icons">
            {socialItems.map((i) => (
              <div className="icon" key={i.href}>
                <a href={i.href} target="_blank">
                  <FontAwesomeIcon icon={i.icon!} size={"lg"} />
                </a>
              </div>
            ))}
          </div>
        </div>
        <div className="image">
          <img src={"/img/adam.jpg"} />
        </div>
      </div>
    </div>
  );
}

export default Header;
