// src/DesktopNavigation.tsx
import "./DesktopNavigation.scss";
import { ExternalNavigationItem, NavigationItem } from "./models";

interface DesktopNavigationProps {
  navigationItems: NavigationItem[];
  externalNavigationItems: ExternalNavigationItem[];
}

function DesktopNavigation({
  navigationItems,
  externalNavigationItems,
}: DesktopNavigationProps) {
  const navigate = (fragment?: string) => {
    if (fragment) {
      setTimeout(() => {
        scrollToElement(fragment);
      }, 1);
    }
    return undefined;
  };

  const scrollToElement = (id: string) => {
    const element = document.querySelector(`#${id}`);
    element && element.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <div className="desktop-navigation card">
      <div className="card-content">
        <ul className="internal-items">
          {navigationItems.map((i) => (
            <li key={i.title}>
              <a onClick={() => navigate(i.fragment)}>{i.title}</a>
            </li>
          ))}
        </ul>
        <ul className="external-items">
          {externalNavigationItems.map((i) => (
            <li key={i.title}>
              <a href={i.url} target="_blank">
                {i.title}
              </a>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}

export default DesktopNavigation;

// adam-swanson-site/src/app/navigation/desktop-navigation/desktop-navigation.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { ExternalNavigationItem, NavigationItem } from 'src/app/models';

@Component({
  selector: 'app-desktop-navigation',
  templateUrl: './desktop-navigation.component.html',
  styleUrls: ['./desktop-navigation.component.scss']
})
export class DesktopNavigationComponent implements OnInit {

  @Input() navigationItems: NavigationItem[];
  @Input() externalNavigationItems: ExternalNavigationItem[];

  constructor() { }

  ngOnInit(): void {
  }

  navigate(fragment: string) {
    const element = document.querySelector(`#${fragment}`);
    element.scrollIntoView({ behavior: 'smooth' });
  }

}

<div class="desktop-navigation card">
  <div class="card-content">
    <ul class="internal-items">
      <li *ngFor="let item of navigationItems">
        <a (click)="navigate(item.fragment)">{{item.title}}</a>
      </li>
    </ul>
    <ul class="external-items">
      <li *ngFor="let item of externalNavigationItems">
        <a [href]="item.url" target="_blank">{{item.title}}</a>
      </li>
    </ul>
  </div>
</div>
