// adam-swanson-site/src/app/navigation/mobile-navigation/mobile-navigation.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { faBars } from '@fortawesome/free-solid-svg-icons';
import { ExternalNavigationItem, NavigationItem } from 'src/app/models';

@Component({
  selector: 'app-mobile-navigation',
  templateUrl: './mobile-navigation.component.html',
  styleUrls: ['./mobile-navigation.component.scss']
})
export class MobileNavigationComponent implements OnInit {

  @Input() navigationItems: NavigationItem[];
  @Input() externalNavigationItems: ExternalNavigationItem[];

  faBars = faBars;
  navigationOpen = false;

  constructor() { }

  ngOnInit(): void {
  }

  toggleNavigation() {
    this.navigationOpen = !this.navigationOpen;
  }

  navigate(fragment?: string) {
    this.navigationOpen = false;
    if (fragment) {
      setTimeout(() => {
        this.scrollToElement(fragment);
      }, 1);
    }
  }

  private scrollToElement(id: string) {
    const element = document.querySelector(`#${id}`);
    element.scrollIntoView({ behavior: 'smooth' });
  }
}

<div class="mobile-nav-spacer"></div>
<div class="mobile-navigation">
  <fa-icon [icon]="faBars" size="lg" (click)="toggleNavigation()"></fa-icon>
  <ul class="internal-items" *ngIf="navigationOpen">
    <li *ngFor="let item of navigationItems">
      <a (click)="navigate(item.fragment)">{{item.title}}</a>
    </li>
  </ul>
  <ul *ngIf="navigationOpen">
    <li *ngFor="let item of externalNavigationItems">
      <a [href]="item.url" target="_blank" (click)="navigate()">{{item.title}}</a>
    </li>
  </ul>
</div>

// src/MobileNavigation.tsx
import { useState } from "react";
import "./MobileNavigation.scss";
import { ExternalNavigationItem, NavigationItem } from "./models";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faBars } from "@fortawesome/free-solid-svg-icons";

interface MobileNavigationProps {
  navigationItems: NavigationItem[];
  externalNavigationItems: ExternalNavigationItem[];
}

function MobileNavigation({
  navigationItems,
  externalNavigationItems,
}: MobileNavigationProps) {
  const [navigationOpen, setNavigationOpen] = useState(false);

  const toggleNavigation = () => {
    setNavigationOpen(!navigationOpen);
  };

  const navigate = (fragment?: string) => {
    if (fragment) {
      setTimeout(() => {
        scrollToElement(fragment);
      }, 1);
      setNavigationOpen(false);
    }
    return undefined;
  };

  const scrollToElement = (id: string) => {
    const element = document.querySelector(`#${id}`);
    element && element.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <>
      <div className="mobile-nav-spacer"></div>
      <div className="mobile-navigation">
        <div className="icon" onClick={() => toggleNavigation()}>
          <FontAwesomeIcon icon={faBars} size={"lg"} />
        </div>
        {navigationOpen && (
          <>
            <ul className="internal-items">
              {navigationItems.map((i) => (
                <li onClick={() => navigate(i.fragment)} key={i.title}>
                  <a>{i.title}</a>
                </li>
              ))}
            </ul>
            <ul>
              {externalNavigationItems.map((i) => (
                <li key={i.title}>
                  <a href={i.url} target="_blank">
                    {i.title}
                  </a>
                </li>
              ))}
            </ul>
          </>
        )}
      </div>
    </>
  );
}

export default MobileNavigation;
